"""Make users id autoincrement

Revision ID: 7c999d0c5044
Revises: 93db670ec850
Create Date: 2023-07-24 09:39:50.712975

"""


# revision identifiers, used by Alembic.
revision = '7c999d0c5044'
down_revision = '93db670ec850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
