"""Create user model

Revision ID: 93db670ec850
Revises:
Create Date: 2023-07-21 10:26:13.025477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93db670ec850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=225), nullable=False),
        sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
        sa.Column('first_name', sa.String(length=225), nullable=False),
        sa.Column('last_name', sa.String(length=225), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
